from __future__ import annotations

from hashlib import sha1

from apartment_bot.core.models import Listing, ListingSource
from apartment_bot.core.normalize import infer_completeness_score


def _listing_id(source: str, url: str) -> str:
    return f"{source}_{sha1(url.encode('utf-8')).hexdigest()[:12]}"


def build_seed_listing(source: str, url: str) -> Listing:
    templates = {
        "craigslist": {
            "source": ListingSource.CRAIGSLIST,
            "address": "North Beach, San Francisco, CA",
            "rent": 4695,
            "beds": 2,
            "baths": 1,
            "sqft": 920,
            "lat": 37.7992,
            "lng": -122.4090,
            "description": "Sample Craigslist seed listing for v1 wiring. In-unit laundry, dishwasher, natural light, updated kitchen, walkable dining.",
            "features": ["in-unit laundry", "dishwasher", "natural light", "updated kitchen"],
            "has_dishwasher": True,
            "has_in_unit_laundry": True,
            "has_parking": False,
            "pet_friendly": True,
            "has_private_outdoor_space": False,
            "has_fitness_center": False,
            "natural_light_signal": True,
            "renovated_kitchen_signal": True,
            "quiet_street_signal": True,
            "caltrain_signal": False,
            "walkability_signal": True,
            "street_parking_only": True,
            "older_interiors_signal": False,
            "ground_floor_signal": False,
            "unclear_availability_signal": False,
            "broker_fee_signal": False,
        },
        "zillow": {
            "source": ListingSource.ZILLOW,
            "address": "Mission Bay, San Francisco, CA",
            "rent": 5250,
            "beds": 2,
            "baths": 2,
            "sqft": 980,
            "lat": 37.7707,
            "lng": -122.3915,
            "description": "Sample Zillow seed listing for Mission Bay. In-unit laundry, dishwasher, parking, fitness center, private outdoor space, close to Caltrain.",
            "features": ["in-unit laundry", "dishwasher", "parking", "fitness center", "private outdoor space"],
            "has_dishwasher": True,
            "has_in_unit_laundry": True,
            "has_parking": True,
            "pet_friendly": True,
            "has_private_outdoor_space": True,
            "has_fitness_center": True,
            "natural_light_signal": True,
            "renovated_kitchen_signal": True,
            "quiet_street_signal": False,
            "caltrain_signal": True,
            "walkability_signal": True,
            "street_parking_only": False,
            "older_interiors_signal": False,
            "ground_floor_signal": False,
            "unclear_availability_signal": False,
            "broker_fee_signal": False,
        },
        "apartments_com": {
            "source": ListingSource.APARTMENTS_DOT_COM,
            "address": "Mission Bay, San Francisco, CA",
            "rent": 5580,
            "beds": 2,
            "baths": 2,
            "sqft": 870,
            "lat": 37.7740,
            "lng": -122.3912,
            "description": "Sample Apartments.com seed listing for v1 wiring. In-unit laundry, dishwasher, parking, pet friendly, newer appliances.",
            "features": ["in-unit laundry", "dishwasher", "parking", "pet friendly", "newer appliances"],
            "has_dishwasher": True,
            "has_in_unit_laundry": True,
            "has_parking": True,
            "pet_friendly": True,
            "has_private_outdoor_space": False,
            "has_fitness_center": True,
            "natural_light_signal": False,
            "renovated_kitchen_signal": True,
            "quiet_street_signal": False,
            "caltrain_signal": True,
            "walkability_signal": True,
            "street_parking_only": False,
            "older_interiors_signal": False,
            "ground_floor_signal": True,
            "unclear_availability_signal": False,
            "broker_fee_signal": False,
        },
    }
    template = templates[source]
    listing_id = _listing_id(source, url)
    return Listing.now(
        listing_id=listing_id,
        source=template["source"],
        source_listing_id=url,
        address=template["address"],
        rent=template["rent"],
        beds=template["beds"],
        baths=template["baths"],
        sqft=template["sqft"],
        description=template["description"],
        features=template["features"],
        listing_url=url,
        images=[],
        lat=template["lat"],
        lng=template["lng"],
        has_dishwasher=template["has_dishwasher"],
        has_in_unit_laundry=template["has_in_unit_laundry"],
        has_parking=template["has_parking"],
        pet_friendly=template["pet_friendly"],
        has_private_outdoor_space=template["has_private_outdoor_space"],
        has_fitness_center=template["has_fitness_center"],
        natural_light_signal=template["natural_light_signal"],
        renovated_kitchen_signal=template["renovated_kitchen_signal"],
        quiet_street_signal=template["quiet_street_signal"],
        caltrain_signal=template["caltrain_signal"],
        walkability_signal=template["walkability_signal"],
        street_parking_only=template["street_parking_only"],
        older_interiors_signal=template["older_interiors_signal"],
        ground_floor_signal=template["ground_floor_signal"],
        unclear_availability_signal=template["unclear_availability_signal"],
        broker_fee_signal=template["broker_fee_signal"],
        completeness_score=infer_completeness_score(template["address"], template["rent"], template["description"], []),
        raw_payload={"seed_mode": True, "source_url": url},
    )
